server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_registration
    username: postgres
    password: bond007
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true

